services:
  mc:
    env_file:
      - ./stack.env
    image: itzg/minecraft-server
    container_name: fabric-server
    tty: true
    stdin_open: true
    ports: 
      - "25565:25565"
      - "8100:8100"
      - "24454:24454/udp"
    environment:
      EULA: "TRUE"
      VERSION: "1.20.1"
      TYPE: "FABRIC"
      MODRINTH_PROJECTS: ${MODRINTH_PROJECTS}
      MODRINTH_DOWNLOAD_DEPENDENCIES: "NONE"
      MODRINTH_ALLOWED_VERSION_TYPE: "ALPHA"
    volumes:
      - ./fabric-server-data:/data
      - ./fabric-server-configs:/config
      - ./fabric-server-mods:/mods
