config:
  bind: 0.0.0.0:25565
  lite: 
    enabled: true
    routes: 
      - host: "*"
        backend: localhost:25566
        fallback:
          motd: §eGate could not find a backend server.
          version: 
            name: §eError.
            protocol: -1
  connect: 
    enabled: true
    name: YOUR-ENDPOINT-NAME-HERE
